# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list

  download-redis:
    cmds:
      - wget -O redis-6.2.6.tar.gz https://download.redis.io/releases/redis-6.2.6.tar.gz
      - tar -xvf redis-6.2.6.tar.gz
    status:
      - test -f redis-6.2.6.tar.gz
  
  build-redis:
    deps: [download-redis]
    dir: ./redis-6.2.6
    cmds:
      - make
    status:
      - test -f src/redis-server

  run-redis:
    deps: [build-redis]
    dir: ./redis-6.2.6
    cmds:
      - sudo sysctl vm.overcommit_memory=1
      - echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
      - ./src/redis-server