# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list

  download-kafka:
    cmds:
      - wget -O kafka_2.13-3.0.0.tgz https://dlcdn.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz
      - tar -xvf kafka_2.13-3.0.0.tgz    
    status:
      - test -f kafka_2.13-3.0.0.tgz
      - test -d kafka_2.13-3.0.0

  run-zookeeper:
    deps: [download-kafka]
    dir: ./kafka_2.13-3.0.0
    cmds:
      - bin/zookeeper-server-start.sh config/zookeeper.properties

  run-kafka:
    dir: ./kafka_2.13-3.0.0
    cmds:
      - bin/kafka-server-start.sh config/server.properties

  delete-topic:
    dir: ./kafka_2.13-3.0.0
    vars:
      TOPIC: '{{default "nexmark_src" .TOPIC}}'
    cmds:
      - ./bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic {{.TOPIC}}

  print-nexmark-topic:
    dir: ./kafka_2.13-3.0.0
    vars:
      TOPIC: '{{default "nexmark_src" .TOPIC}}'
    cmds:
      - ./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092
        --topic {{.TOPIC}} --from-beginning
        --formatter kafka.tools.DefaultMessageFormatter
