# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list

  download-kafka:
    desc: "download kafka"
    cmds:
      - wget -O kafka_2.13-3.0.0.tgz https://dlcdn.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz
      - tar -xvf kafka_2.13-3.0.0.tgz    
    status:
      - test -f kafka_2.13-3.0.0.tgz
      - test -d kafka_2.13-3.0.0

  run-zookeeper:
    desc: "run zookeeper"
    deps: [download-kafka]
    dir: ./kafka_2.13-3.0.0
    cmds:
      - bin/zookeeper-server-start.sh config/zookeeper.properties

  run-kafka:
    desc: "run a single instance kafka"
    dir: ./kafka_2.13-3.0.0
    cmds:
      - bin/kafka-server-start.sh config/server.properties

  delete-topic:
    desc: "delete topic"
    dir: ./kafka_2.13-3.0.0
    vars:
      TOPIC: '{{default "nexmark_src" .TOPIC}}'
      ZOOKEEPER: '{{default "localhost:2181" .ZOOKEEPER}}'
    cmds:
      - ./bin/kafka-topics.sh --zookeeper {{.ZOOKEEPER}} --delete --topic {{.TOPIC}}

  print-topic:
    desc: "print a topic"
    dir: ./kafka_2.13-3.0.0
    vars:
      TOPIC: '{{default "nexmark_src" .TOPIC}}'
      BOOTSTRAP: '{{default "localhost:9092" .BOOTSTRAP}}'
    cmds:
      - ./bin/kafka-console-consumer.sh --bootstrap-server {{.BOOTSTRAP}}
        --topic {{.TOPIC}} --property print.timestamp=true --from-beginning {{.CLI_ARGS}}
