# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list

  build:
    desc: "build nexmark kafka implementation"
    cmds:
      - gradle uberJar
    sources:
      - src/main/java/com/github/nexmark/kafka/**/*.java
    generates:
      - target/nexmark-kafka-streams-0.2-SNAPSHOT-uber.jar

  run-query:
    desc: "run query"
    deps: [build]
    dir: ./build
    cmds:
      - java -cp ./libs/nexmark-kafka-streams-0.2-SNAPSHOT-uber.jar com.github.nexmark.kafka.queries.RunQuery {{.CLI_ARGS}}
